### chat signup jack

POST http://localhost:6688/api/signup
Content-Type: application/json

{
    "workspace": "acme",
    "fullname": "jack",
    "email": "jack@gmail.com",
    "password": "Hunter48"
}

### chat signup jack1

POST http://localhost:6688/api/signup
Content-Type: application/json

{
    "workspace": "acme",
    "fullname": "jack1",
    "email": "jack1@gmail.com",
    "password": "Hunter48"
}

### chat signin (invalid)

POST http://localhost:6688/api/signin
Content-Type: application/json

{
    "email": "non-exist@gmail.com",
    "password": "Hunter48"
}

### chat signin (valid)
# @name signin

POST http://localhost:6688/api/signin
Content-Type: application/json

{
    "email": "jack@gmail.com",
    "password": "Hunter48"
}

@token = {{signin.response.body.token}}

### create chat api
POST http://localhost:6688/api/chats
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "members": [1, 2],
    "public": false
}

### get chat api
GET http://localhost:6688/api/chats
Authorization: Bearer {{token}}

### delete chat api
DELETE http://localhost:6688/api/chats/1
Authorization: Bearer {{token}}

### get user list of workspace
GET http://localhost:6688/api/users
Authorization: Bearer {{token}}
