### chat signup

POST http://localhost:6688/api/signup
Content-Type: application/json

{
    "fullname": "jack",
    "email": "jack@gmail.com",
    "password": "Hunter48"
}

### chat signin (invalid)

POST http://localhost:6688/api/signin
Content-Type: application/json

{
    "email": "non-exist@gmail.com",
    "password": "Hunter48"
}

### chat signin (valid)
# @name signin

POST http://localhost:6688/api/signin
Content-Type: application/json

{
    "email": "jack@gmail.com",
    "password": "Hunter48"
}

@token = {{signin.response.body.token}}

### chat api
GET http://localhost:6688/api/chat
Authorization: Bearer {{token}}
