server:
  port: 6688
  db_url: postgres://postgres:postgres@localhost:5432/chat
auth:
  sk: |
    -----BEGIN PRIVATE KEY-----
    MC4CAQAwBQYDK2VwBCIEIJL4hlV1fEGZHFLkhQ99g7MwDwJ+DwXfYZv18fLcj07y
    -----END PRIVATE KEY-----
  pk: |
    -----BEGIN PUBLIC KEY-----
    MCowBQYDK2VwAyEA9Q0GlRpk0eQY/35d414jJ9l6k5xH1SDKCQwg6z/lTmQ=
    -----END PUBLIC KEY-----
